spring:
  application:
    name: gateway
  cloud:
    gateway:
        routes:
          - id: charge-station-service
            uri: http://charge-station-service:8081
            predicates:
              - Path=/stations/**
          - id: StationDataRelayService
            uri: http://station-data-relay-service:8083
            predicates:
              - Path=/fetch/**
