spring:
  application:
    name: gateway
  cloud:
    gateway:
        routes:
          - id: charge-station-service
            uri:
              http://localhost:8081
            predicates:
              - Path=/stations/**
