services:
  postgres:
    container_name: station
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: station
    volumes:
      - postgres:/data/postgres
    ports:
      - 5433:5432
    networks:
      - spring-demo
    restart: unless-stopped
  redis:
    container_name: redis-station
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - spring-demo
    restart: unless-stopped
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper2
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - spring-demo
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka2
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
    restart: unless-stopped
    depends_on:
      - zookeeper
    networks:
      - spring-demo



volumes:
  postgres:
    driver: local


networks:
  spring-demo:
    driver: bridge
