FROM openjdk:21
WORKDIR /app
COPY mvnw .
COPY .mvn .mvn
COPY pom.xml /app/
RUN chmod +x mvnw
RUN ./mvnw dependency:go-offline
COPY src /app/src
RUN ./mvnw clean package -DskipTests
COPY ./target/gateway-0.0.1-SNAPSHOT.jar /app/gateway.jar
EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app/gateway.jar"]
