# Use OpenJDK 21 as the base image
FROM openjdk:21

# Set the working directory
WORKDIR /app

# Copy the Maven Wrapper files and pom.xml
COPY mvnw .
COPY .mvn .mvn
COPY pom.xml /app/

# Give executable permissions to the Maven Wrapper
RUN chmod +x mvnw

# Copy the local dependency to the Maven repository
COPY ./common-dto-module-0.0.1-SNAPSHOT.jar /root/.m2/repository/com/kodat/of/common-dto-module/0.0.1-SNAPSHOT/common-dto-module-0.0.1-SNAPSHOT.jar

# Download dependencies
RUN ./mvnw dependency:go-offline

# Copy the source code
COPY src /app/src

# Build the application with Maven
RUN ./mvnw clean package -DskipTests

# Copy the JAR file to the container
COPY ./target/StationDataRelayService-0.0.1-SNAPSHOT.jar /app/stationDataRelayService.jar

# Expose the port the container will listen on
EXPOSE 8083

# Set the entrypoint to run the application
ENTRYPOINT ["java", "-jar", "/app/stationDataRelayService.jar"]
