spring:
  application:
    name: charge-station-service
  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5433/station
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      port: 6379
      host: redis-station

  cache:
    type: redis
    cache-names:
      - stations
      - station
    redis:
      key-prefix: charge-station-service
server:
  port: 8081

