apiVersion: v1
kind: ConfigMap
metadata:
  name: charge-station-service
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/station"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_REDIS_HOST: "redis"
  SPRING_REDIS_PORT: "6379"
  SPRING_CACHE_TYPE: "redis"
  SPRING_CACHE_REDIS_KEY_PREFIX: "charge-station-service"
  SPRING_CACHE_REDIS_CACHE_NAMES: "stations,station"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  SPRING_KAFKA_CONSUMER_GROUP_ID: "charge-station-consumer-service"
  SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER: "org.apache.kafka.common.serialization.StringDeserializer"
  SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER: "org.springframework.kafka.support.serializer.JsonDeserializer"
  SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET: "latest"


